sudo: required
env:
    - QT=5
jobs:
    include:
        - os: linux
          dist: trusty
          env: QT_REPO=ppa:beineri/opt-qt591-trusty QT_PREFIX=59
        - os: linux
          dist: bionic
          env: QT_REPO=ppa:beineri/opt-qt-5.14.0-bionic QT_PREFIX=514
        - os: osx
          osx_image: xcode11.3
        - os: windows
git:
    depth: 9999999
language: sh

install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./ci/travis-linux-install.sh; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ];   then ./ci/travis-osx-install.sh;   fi
    - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then  powershell -executionpolicy bypass -file ci\\travis-windows-install.ps1;   fi

script:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./ci/travis-linux-script.sh; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ];   then ./ci/travis-osx-script.sh;   fi
    - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then  powershell -executionpolicy bypass -file ci\\travis-windows-script.ps1;   fi

deploy:
    skip_cleanup: true
    on:
        branch:
            - ci-test
            - master
        condition: $TRAVIS_OS_NAME != linux
    provider: bintray
    file: binaries/bin/deploy.json
    user: krakonos
    key:
      secure: CMTTCxFAUirt3f+LOOC3ngJKzyqNuLO1il4Vmd8Jq5isAfiiShzs0Qj+8vvsdl7ebyVBQ5srTmwOY1z6B/Jzl5gpHPR3Y2oYt4hFaAkKU6nnlCELX7N/pS1TAXgX8NZjjod0xlfV2700eWDDBRs7gjGWQKhKzRVlMByWYeWV68c=
